---
   - name : Find files older than 30 days
     find:
       paths: /var/log
       patterns: '*'
       age: 30d
       age_stamp: mtime
     register: output

#   - debug: var=item.path
#     with_items: "{{ output.files }}"


   - name: Ansible find files in directory "/var/log"
     debug:
       msg: "{{ output['files'] | map(attribute='path') |list }}"
